source "https://rubygems.org"

gem 'chef'
gem 'berkshelf'
gem 'guard'
gem 'guard-bundler'
gem 'guard-rspec'
gem 'rb-fsevent'
gem 'chefspec'
gem 'test-kitchen'
group :integration do
  # gem 'test-kitchen'
  gem 'kitchen-vagrant', '~> 0.11'
end
